### ISSUE TITLE
No curl inside PKS-SIP for health check

### ISSUE THREAD

**Issue by mostafa0017** [mwolff44/pk-sbc#206]
**Describe the bug**
pks-sip container always shows as (unhealthy)

**To Reproduce**
pks start
pks-sip container doesn't have curl and gives
```
"ExitCode": 1,
"Output": "/bin/sh: 1: curl: not found\n"
```

**Expected behavior**
Curl to be installed inside pks-sip and the container reports its health.

**Comment by mwolff44** [comment]
Hi,
Thanks for the report.
I updated the docker file.
Mathias

**Comment by insxa** [comment]
I have installed docker and docker composer and bash install but how to access admin ?
